name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # daily at midnight
  workflow_dispatch:

permissions:
  contents: write  # Allow push to the repo

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Light mode snake
      - name: Generate Snake (light)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: kavinpradheep
          outputs: dist/github-contribution-grid-snake.svg

      # Dark mode snake
      - name: Generate Snake (dark)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: kavinpradheep
          outputs: dist/github-contribution-grid-snake-dark.svg
          palette: github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
