name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write  # This is required to push the SVGs

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake SVGs (light + dark)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: kavinpradheep
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
